name: "monhan-app-actions"
on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print is ok?
        run: echo "Actions runs on ${{github.head_ref}} "
